// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZEbrKL1-31EOm468IW_UgpOhlOBB8Ggg',
    appId: '1:965407057492:web:bc13876bb6ccb7d1efafc1',
    messagingSenderId: '965407057492',
    projectId: 'eloa-48c62',
    authDomain: 'eloa-48c62.firebaseapp.com',
    storageBucket: 'eloa-48c62.firebasestorage.app',
    measurementId: 'G-BZ0BJJFWC8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi6iN-B6hh8NLLHRScDgckUf6G0XqVKqU',
    appId: '1:965407057492:android:81f2dbb02ecde9eeefafc1',
    messagingSenderId: '965407057492',
    projectId: 'eloa-48c62',
    storageBucket: 'eloa-48c62.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAekXj5-obNurHLUcyEL2zD6njzH8pTXJ8',
    appId: '1:965407057492:ios:ec1a93b1fa174dd8efafc1',
    messagingSenderId: '965407057492',
    projectId: 'eloa-48c62',
    storageBucket: 'eloa-48c62.firebasestorage.app',
    iosClientId: '965407057492-bcg07vm39ck4js4d7vvqum8i1t67s4no.apps.googleusercontent.com',
    iosBundleId: 'com.koralabs.eloa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAekXj5-obNurHLUcyEL2zD6njzH8pTXJ8',
    appId: '1:965407057492:ios:ec1a93b1fa174dd8efafc1',
    messagingSenderId: '965407057492',
    projectId: 'eloa-48c62',
    storageBucket: 'eloa-48c62.firebasestorage.app',
    iosClientId: '965407057492-bcg07vm39ck4js4d7vvqum8i1t67s4no.apps.googleusercontent.com',
    iosBundleId: 'com.koralabs.eloa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZEbrKL1-31EOm468IW_UgpOhlOBB8Ggg',
    appId: '1:965407057492:web:21df1ed1417c2d1cefafc1',
    messagingSenderId: '965407057492',
    projectId: 'eloa-48c62',
    authDomain: 'eloa-48c62.firebaseapp.com',
    storageBucket: 'eloa-48c62.firebasestorage.app',
    measurementId: 'G-TBYVZ704DM',
  );
}
